// Homepage-spezifische Produkte (独立的首页产品数据)
export const homepageProducts = [
  {
    id: 'hp-1',
    name: 'Adobe Creative Cloud',
    type: 'account',
    category: 'design',
    price: 648.00,
    originalPrice: 780.00,
    discount: 17,
    currency: 'CHF',
    billingCycle: 'yearly',
    description: 'Complete Adobe Creative Suite with 20+ professional apps',
    image: '/logos/adobe.png',
    badge: 'POPULAR',
    href: '/product/adobe-creative-cloud',
  },
  {
    id: 'hp-2',
    name: 'JetBrains All Products',
    type: 'account',
    category: 'program',
    price: 99.90,
    originalPrice: 685.00,
    discount: 85,
    currency: 'CHF',
    billingCycle: 'yearly',
    description: 'Complete JetBrains toolbox with all IDEs',
    image: '/logos/jetbrains.png',
    badge: 'SAVE 85%',
    href: '/product/jetbrains-all-products',
  },
  {
    id: 'hp-3',
    name: 'Axure RP 10 Team',
    type: 'key',
    category: 'design',
    price: 99.90,
    originalPrice: 440.00,
    discount: 77,
    currency: 'CHF',
    billingCycle: 'yearly',
    description: 'Professional prototyping and wireframing tool',
    image: '/logos/axure.png',
    badge: 'BEST DEAL',
    href: '/product/axure-rp-10',
  },
];

// Carousel Produkte für Homepage
export const carouselProducts = [
  {
    id: 'carousel-1',
    name: 'Navicat Premium',
    type: 'key',
    category: 'program',
    price: 99.90,
    originalPrice: 350.00,
    discount: 71,
    currency: 'CHF',
    billingCycle: 'yearly',
    description: 'Universal database management tool',
    image: '/logos/navicat.png',
    badge: 'LIMITED TIME',
    href: '/product/navicat-premium',
  },
  {
    id: 'carousel-2',
    name: 'SecureCRT',
    type: 'key',
    category: 'security',
    price: 72.00,
    originalPrice: 87.00,
    discount: 17,
    currency: 'CHF',
    billingCycle: 'one-time',
    description: 'Professional SSH client for secure remote access',
    image: '/logos/securecrt.png',
    href: '/product/securecrt',
  },
  {
    id: 'carousel-3',
    name: 'Sketch',
    type: 'key',
    category: 'design',
    price: 79.00,
    originalPrice: 120.00,
    discount: 34,
    currency: 'CHF',
    billingCycle: 'yearly',
    description: 'Digital design toolkit for Mac',
    image: '/logos/sketch.png',
    badge: 'NEW',
    href: '/product/sketch',
  },
];

export type HomepageProduct = typeof homepageProducts[0];
