// Search/All Seite Produkte (搜索/全部页面的产品数据)
export const searchProducts = [
  {
    id: 'adobe-creative-cloud',
    name: 'Adobe Creative Cloud',
    type: 'account',
    category: 'design',
    price: 648.00,
    originalPrice: 780.00,
    discount: 17,
    currency: 'CHF',
    billingCycle: 'yearly',
    description: 'Complete Adobe Creative Suite with 20+ professional apps for design, video, web, and photography.',
    image: '/logos/adobe.png',
    badge: 'POPULAR',
  },
  {
    id: 'jetbrains-all-products',
    name: 'JetBrains All Products',
    type: 'account',
    category: 'development',
    price: 99.90,
    originalPrice: 685.00,
    discount: 85,
    currency: 'CHF',
    billingCycle: 'yearly',
    description: 'Complete JetBrains toolbox with all IDEs for every programming language.',
    image: '/logos/jetbrains.png',
    badge: 'SAVE 85%',
  },
  {
    id: 'axure-rp-10',
    name: 'Axure RP 10 Team',
    type: 'key',
    category: 'design',
    price: 99.90,
    originalPrice: 440.00,
    discount: 77,
    currency: 'CHF',
    billingCycle: 'yearly',
    description: 'Professional prototyping and wireframing tool for UX designers.',
    image: '/logos/axure.png',
    badge: 'BEST DEAL',
  },
  {
    id: 'navicat-premium',
    name: 'Navicat Premium',
    type: 'key',
    category: 'development',
    price: 99.90,
    originalPrice: 350.00,
    discount: 71,
    currency: 'CHF',
    billingCycle: 'yearly',
    description: 'Universal database management tool supporting MySQL, PostgreSQL, MongoDB, and more.',
    image: '/logos/navicat.png',
    badge: 'LIMITED TIME',
  },
  {
    id: 'securecrt',
    name: 'SecureCRT',
    type: 'key',
    category: 'security',
    price: 72.00,
    originalPrice: 87.00,
    discount: 17,
    currency: 'CHF',
    billingCycle: 'one-time',
    description: 'Professional SSH client for secure remote access with advanced terminal emulation.',
    image: '/logos/securecrt.png',
  },
  {
    id: 'sketch',
    name: 'Sketch',
    type: 'key',
    category: 'design',
    price: 79.00,
    originalPrice: 120.00,
    discount: 34,
    currency: 'CHF',
    billingCycle: 'yearly',
    description: 'Digital design toolkit for Mac. Create, prototype, and collaborate.',
    image: '/logos/sketch.png',
    badge: 'NEW',
  },
  {
    id: 'figma-professional',
    name: 'Figma Professional',
    type: 'account',
    category: 'design',
    price: 144.00,
    originalPrice: 180.00,
    discount: 20,
    currency: 'CHF',
    billingCycle: 'yearly',
    description: 'Collaborative interface design tool for teams. Design, prototype, and gather feedback.',
    image: '/logos/figma.png',
  },
  {
    id: 'github-copilot',
    name: 'GitHub Copilot',
    type: 'account',
    category: 'development',
    price: 99.00,
    originalPrice: 120.00,
    discount: 18,
    currency: 'CHF',
    billingCycle: 'yearly',
    description: 'AI pair programmer that helps you write code faster with contextual suggestions.',
    image: '/logos/github.png',
    badge: 'AI POWERED',
  },
  {
    id: '1password-teams',
    name: '1Password Teams',
    type: 'account',
    category: 'security',
    price: 47.88,
    originalPrice: 60.00,
    discount: 20,
    currency: 'CHF',
    billingCycle: 'yearly',
    description: 'Secure password manager for teams. Share passwords and sensitive data safely.',
    image: '/logos/1password.png',
  },
  {
    id: 'notion-team',
    name: 'Notion Team',
    type: 'account',
    category: 'productivity',
    price: 96.00,
    originalPrice: 120.00,
    discount: 20,
    currency: 'CHF',
    billingCycle: 'yearly',
    description: 'All-in-one workspace for notes, docs, wikis, and project management.',
    image: '/logos/notion.png',
  },
];

// Kategorien für Filter
export const categories = [
  { id: '', name: 'All' },
  { id: 'design', name: 'Design' },
  { id: 'development', name: 'Development' },
  { id: 'security', name: 'Security' },
  { id: 'productivity', name: 'Productivity' },
];

export type SearchProduct = typeof searchProducts[0];
