/* 维基词条，用来拉公开缩略图。查不到就显示姓名缩写。 */
const PORTRAITS = {
  "egypt-nk": { wiki: "新王国时期", people: { "拉美西斯二世": "拉美西斯二世", "图特摩斯三世": "图特摩斯三世", "阿肯那顿": "阿肯那顿", "奈菲尔提蒂": "奈菲尔提蒂" } },
  "egypt-ok": { wiki: "古王国时期", people: { "胡夫": "胡夫", "左塞尔": "左塞尔", "哈夫拉": "哈夫拉" } },
  "hittite": { wiki: "赫梯" },
  "assyria": { wiki: "新亚述帝国", people: { "亚述巴尼拔": "亚述巴尼拔" } },
  "babylon": { wiki: "新巴比伦帝国", people: { "尼布甲尼撒二世": "尼布甲尼撒二世" } },
  "old-babylon": { wiki: "古巴比伦时期", people: { "汉谟拉比": "汉谟拉比" } },
  "achaemenid": { wiki: "阿契美尼德王朝", people: { "居鲁士大帝": "居鲁士二世", "大流士一世": "大流士一世", "薛西斯一世": "薛西斯一世" } },
  "shang": { wiki: "商朝", people: { "妇好": "妇好", "武丁": "武丁" } },
  "zhou": { wiki: "周朝", people: { "周武王": "周武王", "周公旦": "周公旦" } },
  "chu": { wiki: "楚国", people: { "屈原": "屈原", "楚庄王": "楚庄王" } },
  "qin": { wiki: "秦朝", people: { "秦始皇": "秦始皇", "商鞅": "商鞅", "李斯": "李斯", "秦孝公": "秦孝公" } },
  "han": { wiki: "汉朝", people: { "刘邦": "刘邦", "汉武帝": "汉武帝", "光武帝": "光武帝" } },
  "xiongnu": { wiki: "匈奴", people: { "冒顿单于": "冒顿单于" } },
  "macedonia": { wiki: "亚历山大帝国", people: { "亚历山大大帝": "亚历山大大帝", "腓力二世": "马其顿的腓力二世" } },
  "ptolemy": { wiki: "托勒密王朝", people: { "克娄巴特拉七世": "克娄巴特拉七世", "托勒密一世": "托勒密一世" } },
  "seleucid": { wiki: "塞琉古帝国" },
  "maurya": { wiki: "孔雀王朝", people: { "阿育王": "阿育王", "旃陀罗笈多": "旃陀罗笈多" } },
  "rome": { wiki: "罗马帝国", people: { "凯撒": "尤利乌斯·凯撒", "奥古斯都": "奥古斯都", "图拉真": "图拉真", "奥勒留": "马可·奥勒留" } },
  "parthia": { wiki: "帕提亚帝国" },
  "sassanid": { wiki: "萨珊王朝" },
  "byzantium": { wiki: "拜占庭帝国", people: { "查士丁尼": "查士丁尼一世", "君士坦丁": "君士坦丁大帝" } },
  "gupta": { wiki: "笈多王朝" },
  "aksum": { wiki: "阿克苏姆王国" },
  "tang": { wiki: "唐朝", people: { "李世民": "唐太宗", "武则天": "武则天", "唐玄宗": "唐玄宗", "杨贵妃": "杨贵妃" } },
  "sui": { wiki: "隋朝", people: { "杨坚": "隋文帝", "杨广": "隋炀帝" } },
  "wei": { wiki: "曹魏", people: { "曹操": "曹操", "曹丕": "曹丕", "曹植": "曹植" } },
  "jin": { wiki: "晋朝", people: { "司马懿": "司马懿" } },
  "silla": { wiki: "新罗" },
  "yamato": { wiki: "天皇", people: { "圣德太子": "圣德太子", "推古天皇": "推古天皇" } },
  "fujiwara": { wiki: "藤原氏", people: { "藤原道长": "藤原道长" } },
  "rashidun": { wiki: "正统哈里发", people: { "欧麦尔": "欧麦尔·本·哈塔卜", "阿里": "阿里·本·阿比·塔利卜" } },
  "umayyad": { wiki: "倭马亚王朝" },
  "abbasid": { wiki: "阿拔斯王朝", people: { "哈伦·拉希德": "哈伦·拉希德" } },
  "umayyad-cordoba": { wiki: "后倭马亚王朝" },
  "carolingian": { wiki: "加洛林王朝", people: { "查理曼": "查理曼" } },
  "capet": { wiki: "卡佩王朝" },
  "plantagenet": { wiki: "金雀花王朝", people: { "狮心王理查": "理查一世 (英格兰)", "亨利二世": "亨利二世 (英格兰)" } },
  "seljuk": { wiki: "塞尔柱帝国" },
  "chola": { wiki: "朱罗王朝" },
  "angkor": { wiki: "吴哥帝国", people: { "苏利耶跋摩二世": "苏利耶跋摩二世" } },
  "mali": { wiki: "马里帝国", people: { "曼萨·穆萨": "曼萨·穆萨", "松迪亚塔": "松迪亚塔·凯塔" } },
  "songhai": { wiki: "桑海帝国" },
  "mongol": { wiki: "蒙古帝国", people: { "成吉思汗": "成吉思汗", "忽必烈": "忽必烈", "窝阔台": "窝阔台" } },
  "song": { wiki: "宋朝", people: { "赵匡胤": "赵匡胤", "岳飞": "岳飞", "文天祥": "文天祥" } },
  "yuan": { wiki: "元朝", people: { "忽必烈": "忽必烈" } },
  "golden-horde": { wiki: "金帐汗国" },
  "ilkhans": { wiki: "伊儿汗国", people: { "旭烈兀": "旭烈兀" } },
  "ming": { wiki: "明朝", people: { "朱元璋": "朱元璋", "永乐帝": "明成祖", "崇祯": "崇祯帝" } },
  "joseon": { wiki: "朝鲜王朝", people: { "世宗": "朝鲜世宗", "李成桂": "李成桂" } },
  "timurid": { wiki: "帖木儿帝国", people: { "帖木儿": "帖木儿" } },
  "ottoman": { wiki: "奥斯曼帝国", people: { "穆罕默德二世": "穆罕默德二世", "苏莱曼大帝": "苏莱曼一世 (奥斯曼帝国)", "奥斯曼一世": "奥斯曼一世" } },
  "safavid": { wiki: "萨非王朝" },
  "mughal": { wiki: "莫卧儿帝国", people: { "阿克巴": "阿克巴", "沙贾汗": "沙贾汉", "巴布尔": "巴布尔", "奥朗则布": "奥朗则布" } },
  "aztec": { wiki: "阿兹特克帝国", people: { "蒙特苏马二世": "蒙特苏马二世" } },
  "inca": { wiki: "印加帝国", people: { "帕查库特克": "帕查库特克", "阿塔瓦尔帕": "阿塔瓦尔帕" } },
  "habsburg": { wiki: "哈布斯堡王朝", people: { "查理五世": "查理五世", "玛丽亚·特蕾莎": "玛丽亚·特蕾莎", "弗朗茨·约瑟夫": "弗朗茨·约瑟夫一世" } },
  "valois": { wiki: "瓦卢瓦王朝" },
  "tudor": { wiki: "都铎王朝", people: { "亨利八世": "亨利八世", "伊丽莎白一世": "伊丽莎白一世", "亨利七世": "亨利七世" } },
  "stuart": { wiki: "斯图亚特王朝", people: { "查理一世": "查理一世 (英格兰)" } },
  "bourbon": { wiki: "波旁王朝", people: { "路易十四": "路易十四", "路易十六": "路易十六", "亨利四世": "亨利四世 (法国)" } },
  "bourbon-spain": { wiki: "西班牙波旁王朝" },
  "romanov": { wiki: "罗曼诺夫王朝", people: { "彼得大帝": "彼得大帝", "叶卡捷琳娜二世": "叶卡捷琳娜二世", "尼古拉二世": "尼古拉二世" } },
  "hanover": { wiki: "汉诺威王朝", people: { "维多利亚": "维多利亚 (英国君主)", "乔治三世": "乔治三世" } },
  "tokugawa": { wiki: "德川幕府", people: { "德川家康": "德川家康", "德川庆喜": "德川庆喜" } },
  "qing": { wiki: "清朝", people: { "康熙": "康熙帝", "乾隆": "乾隆帝", "慈禧": "慈禧太后", "皇太极": "皇太极" } },
  "khorchin": { wiki: "孝庄文皇后", people: { "孝庄文皇后": "孝庄文皇后", "海兰珠": "海兰珠", "僧格林沁": "僧格林沁" } },
  "hohenzollern": { wiki: "霍亨索伦王朝", people: { "腓特烈大帝": "腓特烈二世", "威廉二世": "威廉二世" } },
  "oldenburg": { wiki: "奥尔登堡王朝", people: { "克里斯蒂安九世": "克里斯蒂安九世" } },
  "nguyen": { wiki: "阮朝", people: { "保大帝": "保大帝" } },
  "sumer": { wiki: "乌尔第三王朝" },
  "akkad": { wiki: "阿卡德帝国", people: { "萨尔贡": "萨尔贡大帝" } },
  "carthage": { wiki: "迦太基", people: { "汉尼拔": "汉尼拔" } },
  "tubo": { wiki: "吐蕃", people: { "松赞干布": "松赞干布", "文成公主": "文成公主" } },
  "liao": { wiki: "辽朝", people: { "耶律阿保机": "耶律阿保机", "萧太后": "萧绰" } },
  "xia-west": { wiki: "西夏", people: { "李元昊": "李元昊" } },
  "jin-jurchen": { wiki: "金朝", people: { "完颜阿骨打": "完颜阿骨打" } },
  "goryeo": { wiki: "高丽" },
  "ashikaga": { wiki: "室町幕府", people: { "足利义满": "足利义满" } },
  "merovingian": { wiki: "墨洛温王朝", people: { "克洛维": "克洛维一世" } },
  "normandy": { wiki: "诺曼底公国", people: { "征服者威廉": "威廉一世 (英格兰)" } },
  "castile": { wiki: "卡斯蒂利亚王权", people: { "伊莎贝拉一世": "伊莎贝拉一世 (卡斯蒂利亚)" } },
  "aviz": { wiki: "阿维斯王朝", people: { "恩里克航海王子": "恩里克 (航海家)" } },
  "burgundy": { wiki: "勃艮第公国" },
  "medici": { wiki: "美第奇家族", people: { "洛伦佐": "洛伦佐·德·美第奇", "科西莫": "科西莫·德·美第奇" } },
  "rurik": { wiki: "留里克王朝", people: { "伊凡雷帝": "伊凡四世" } },
  "jagiellon": { wiki: "雅盖隆王朝" },
  "vasa": { wiki: "瓦萨王朝", people: { "古斯塔夫·阿道夫": "古斯塔夫二世·阿道夫" } },
  "savoy": { wiki: "萨伏依王朝" },
  "fatimid": { wiki: "法蒂玛王朝" },
  "ayyubid": { wiki: "阿尤布王朝", people: { "萨拉丁": "萨拉丁" } },
  "mamluk": { wiki: "马穆鲁克王朝" },
  "delhi": { wiki: "德里苏丹国" },
  "pala": { wiki: "波罗王朝" },
  "srivijaya": { wiki: "三佛齐" },
  "vijayanagara": { wiki: "毗奢耶那伽罗王朝" },
  "maratha": { wiki: "马拉塔帝国", people: { "西瓦吉": "希瓦吉" } },
  "ghana": { wiki: "加纳帝国" },
  "almohad": { wiki: "穆瓦希德王朝" },
  "solomonic": { wiki: "所罗门王朝 (埃塞俄比亚)", people: { "海尔·塞拉西": "海尔·塞拉西一世", "孟尼利克二世": "孟尼利克二世" } },
  "kongo": { wiki: "刚果王国" },
  "maya": { wiki: "玛雅文明", people: { "巴加尔大帝": "巴加尔二世" } },
  "toltec": { wiki: "托尔特克" },
  "northern-wei": { wiki: "北魏", people: { "孝文帝": "魏孝文帝" } },
  "dali": { wiki: "大理国" },
  "ryukyu": { wiki: "琉球国" },
  "pagan": { wiki: "蒲甘王国" },
  "majapahit": { wiki: "满者伯夷" },
  "sukhothai": { wiki: "素可泰王国", people: { "兰甘亨": "兰甘亨" } },
  "toungoo": { wiki: "东吁王朝" },
  "lanxang": { wiki: "澜沧王国" },
  "nabataean": { wiki: "纳巴泰人" },
  "qajar": { wiki: "卡扎尔王朝" },
  "piast": { wiki: "皮雅斯特王朝" },
  "arpad": { wiki: "阿尔帕德王朝" },
  "zimbabwe": { wiki: "大津巴布韦" },
  "kanem": { wiki: "卡奈姆-博尔努帝国" },
  "benin": { wiki: "贝宁帝国" },
  "oyo": { wiki: "奥约帝国" },
  "asante": { wiki: "阿散蒂帝国" },
  "wari": { wiki: "瓦里文化" },
  "tiwanaku": { wiki: "蒂亚瓦纳科" },
  "purepecha": { wiki: "普雷佩查人" },
  "muisca": { wiki: "穆伊斯卡人" },
  "teotihuacan": { wiki: "特奥蒂瓦坎" },
  "hawaii": { wiki: "夏威夷王国", people: { "卡美哈梅哈一世": "卡美哈梅哈一世", "利留卡拉尼": "利留卡拉尼" } },
  "rattanakosin": { wiki: "扎克里王朝", people: { "朱拉隆功": "朱拉隆功", "拉玛一世": "拉玛一世" } },
  "konbaung": { wiki: "贡榜王朝" },
  "later-le": { wiki: "后黎朝", people: { "黎利": "黎利" } },
  "champa": { wiki: "占婆" },
  "crimean": { wiki: "克里米亚汗国" },
  "bagrationi": { wiki: "巴格拉季昂王朝", people: { "塔玛丽女王": "塔玛丽 (格鲁吉亚)" } },

  goguryeo: { wiki: "高句丽", people: { "广开土王": "好太王", "朱蒙": "朱蒙" } },
  baekje: { wiki: "百济", people: { "近肖古王": "近肖古王" } },
  kamakura: { wiki: "镰仓幕府", people: { "源赖朝": "源赖朝", "北条政子": "北条政子" } },
  toyotomi: { wiki: "丰臣氏", people: { "丰臣秀吉": "丰臣秀吉" } },
  harsha: { wiki: "戒日王朝", people: { "戒日王": "戒日王" } },
  sikh: { wiki: "锡克帝国", people: { "兰季特·辛格": "兰季特·辛格" } },
  ayutthaya: { wiki: "阿瑜陀耶王国", people: { "纳黎萱": "纳黎萱" } },
  zulu: { wiki: "祖鲁王国", people: { "恰卡": "沙卡", "塞奇瓦约": "塞奇瓦约" } },
  dahomey: { wiki: "达荷美王国", people: { "贝汉津": "贝汉津", "阿加贾": "阿加贾" } },
  lithuania: { wiki: "立陶宛大公国", people: { "格迪米纳斯": "格迪米纳斯", "维陶塔斯": "维陶塔斯" } },
  bulgaria: { wiki: "第一保加利亚帝国", people: { "西美昂一世": "西美昂一世", "阿斯帕鲁赫": "阿斯帕鲁赫" } },
  ghaznavid: { wiki: "伽色尼王国", people: { "马哈茂德": "伽色尼的马哈茂德" } },
  hun: { wiki: "匈人", people: { "阿提拉": "阿提拉" } },
  khazar: { wiki: "可萨人" },
  jerusalem: { wiki: "耶路撒冷王国", people: { "鲍德温四世": "鲍德温四世", "梅丽桑德": "梅丽桑德" } },
  rum: { wiki: "罗姆苏丹国", people: { "基利杰阿尔斯兰二世": "基利杰阿尔斯兰二世" } },
  almoravid: { wiki: "穆拉比特王朝", people: { "优素福·本·塔什芬": "优素福·本·塔什芬" } },
  "qara-khitai": { wiki: "西辽", people: { "耶律大石": "耶律大石" } },
  funj: { wiki: "芬吉苏丹国" }

};

function wikiTitleForHouse(h) {
  return PORTRAITS[h.id]?.wiki || h.name;
}
function wikiTitleForPerson(h, name) {
  return PORTRAITS[h.id]?.people?.[name] || name;
}
